application: eternal-ship-92219
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: note_let_anyone_modify.app

libraries:
- name: jinja2
  version: latest
